[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"

# Solidity compiler
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/"
]

# RPC endpoints (optional - can use direct URLs)
[rpc_endpoints]
base = "https://mainnet.base.org"
polygon = "https://polygon-rpc.com"
arbitrum = "https://arb1.arbitrum.io/rpc"
optimism = "https://mainnet.optimism.io"
ethereum = "https://eth.llamarpc.com"